name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        branch: main
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: pixeltube-backend
        heroku_email: ahmad1911491@gmail.com
